### ISSUE TITLE
Having some issues

### ISSUE THREAD

**Issue by nitech** [samneirinck/SonosSharp#1]
Hi. Thanks for making this library! 

I am having problems getting it to work. There are multiple places I have had to uncomment and change code. 

Like for instance inside SonosController.cs:157 where InitializeAsync is never called. 

I am wondering if the Sonos API has changed since this library was written. 

Any thoughts?

**Comment by nitech** [comment]
I got it working after fiddling a lot with it. I will submit a pull request when I have a little more up running

**Comment by samneirinck** [comment]
Hi,

The library was mainly used for a Windows Phone app I built back in the days, so I'm sure there are quite some missing parts here, unfortunately. 

Since then, I've tried reworking the API and the inner workings, and make it work on .NET core. The progress can be found on the master branch, although it's not stable at all.

So just a warning, I'll happily merge the PR, but some time in the future (not any time soon) the current API will be deprecated and I'll move forward with the .NET core version.

**Comment by nitech** [comment]
Ah, yes, I kind of read that on your blog, just couldn't find the new API. 

.Net Core sounds like the way to go. I agree that we should just let the old API die in peace. 

I see you've put a lot of work into the existing API though. Great work and nicely structured code.

**Comment by asebak** [comment]
any updates on this?

**Comment by asebak** [comment]
I noticed in the new version you were working on FindDevicesFromSonosIpAddress returns null
